// REQ: R19 — WebRTC DataChannels (manual pairing, no signaling server)
// REQ: R2 — Room link + on-screen pairing code join

import { PAIRING_PROTOCOL_VERSION } from './constants'
import type { WhiteboardElement } from './element'
import type { ChatMessage, PinnedMessage } from './chat'
import type { Comment, CommentThread } from './comment'
import type { MemberRecord } from './room'
import type { Snapshot } from './snapshot'

/** Pairing offer generated by the Host/initiator for manual exchange. */
export interface PairingOffer {
  version: typeof PAIRING_PROTOCOL_VERSION
  type: 'offer'
  roomId: string
  peerId: string
  displayName: string
  timestamp: string             // ISO 8601
  verificationCode: string      // short human-readable code (e.g., "FORGE-8A3F")
  sdp: string                   // SDP offer (may be compressed)
  iceCandidates: string[]       // gathered ICE candidates
  checksum: string              // SHA-256 hex digest of the payload (excluding checksum field)
}

/** Pairing answer generated by the joiner in response to an offer. */
export interface PairingAnswer {
  version: typeof PAIRING_PROTOCOL_VERSION
  type: 'answer'
  roomId: string
  peerId: string
  displayName: string
  timestamp: string
  verificationCode: string      // must match the offer's verification code
  sdp: string                   // SDP answer
  iceCandidates: string[]
  checksum: string
}

/** Union of pairing payloads. */
export type PairingPayload = PairingOffer | PairingAnswer

/** Descriptor for a connected WebRTC peer. */
export interface PeerDescriptor {
  peerId: string
  displayName: string
  roomId: string
  connectionState: RTCPeerConnectionState
  dataChannelState: RTCDataChannelState
  connectedAt: string           // ISO 8601
  lastMessageAt: string | null  // ISO 8601
}

/** Types of collaboration messages sent over WebRTC DataChannel. */
export type CollabMessageType =
  | 'element-op'
  | 'chat-op'
  | 'comment-op'
  | 'presence-op'
  | 'approval-op'
  | 'activity-op'
  | 'snapshot-op'
  | 'rollback-op'
  | 'conflict-op'
  | 'sync-request'
  | 'sync-response'

/** Payload for whiteboard element collaboration messages. */
export interface ElementOpPayload {
  operation: 'create' | 'update' | 'delete'
  elementId: string
  element?: WhiteboardElement
}

/** Payload for chat + pin collaboration messages. */
export interface ChatOpPayload {
  operation: 'new' | 'delete' | 'pin' | 'unpin'
  messageId: string
  message?: ChatMessage
  pinned?: PinnedMessage
}

/** Payload for threaded comment collaboration messages. */
export interface CommentOpPayload {
  operation: 'create-thread' | 'append-comment'
  threadId: string
  elementId: string
  thread?: CommentThread
  comment?: Comment
}

/** Payload for membership/approval collaboration messages. */
export interface ApprovalOpPayload {
  operation: 'request' | 'approve' | 'reject' | 'leave'
  memberId: string
  member?: MemberRecord
}

/** Payload for snapshot creation collaboration messages. */
export interface SnapshotOpPayload {
  operation: 'snapshot-created'
  snapshotId: string
  sequenceNumber: number
  snapshot?: Snapshot
}

/** Payload for rollback collaboration messages. */
export interface RollbackOpPayload {
  operation: 'rollback-applied'
  snapshotId: string
  initiatorId: string
  resultingSnapshotId: string
  snapshot?: Snapshot
}

/** Envelope for all collaboration messages over WebRTC DataChannel. */
export interface CollabMessage<T = unknown> {
  type: CollabMessageType
  senderId: string
  timestamp: string             // ISO 8601
  seqNum: number                // monotonic sequence number for ordering
  roomId: string
  payload: T
}

/** Conflict record for tracking detected conflicts (multi-tab or multi-device). */
export interface ConflictRecord {
  conflictId: string
  roomId: string
  conflictType: 'element-overwrite' | 'pin-collision' | 'membership-race' | 'rollback-collision'
  resourceId: string            // the ID of the conflicting resource
  sourceTabOrPeerId: string     // tab ID or peer ID that caused the conflict
  detectedAt: string            // ISO 8601
  resolved: boolean
  resolution?: 'overwrite' | 'discard' | 'merge'
  resolvedAt?: string           // ISO 8601
}
